version: "3"
services:
  employee-jdbc:
    image: naresh240/employee-jdbc:latest
    container_name: employee-jdbc
    ports:
      - 8888:8888
    links:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Naresh#240
      - MYSQL_USER=naresh
      - MYSQL_PASSWORD=Naresh#240
      - MYSQL_DATABASE=mysqldb

